"""Database models (SQLModel) and the LLM extraction contract."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum

from pydantic import BaseModel, Field as PydField
from sqlmodel import Field, SQLModel, UniqueConstraint


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Category(str, Enum):
    """The PRIMARY axis: the trading style an item speaks to. Values are human-readable and
    used verbatim by the LLM. (The tech dimension lives on the secondary ``Approach`` axis.)"""

    TECHNICAL_ANALYSIS = "Technical Analysis"
    MACRO_ANALYSIS = "Macro Analysis"
    INTRADAY_TRADING = "Intraday Trading"
    SWING_TRADING = "Swing Trading"
    FUNDAMENTAL_ANALYSIS = "Fundamental Analysis"
    QUANT_FIRMS = "Quant Firms"


class Approach(str, Enum):
    """The SECONDARY axis: which kind of tech an item uses. Rendered as sub-tags under the
    trading-style category (e.g. "Agentic AI · Intraday Trading"). 0-2 apply to most items."""

    AGENTIC_AI = "Agentic AI"
    MACHINE_LEARNING = "Machine Learning"
    AUTOMATION = "Automation"
    SENTIMENT_NEWS = "Sentiment & News"
    INFRA_DATA = "Infrastructure & Data"
    RISK_SIZING = "Risk & Sizing"


class RawItem(SQLModel, table=True):
    """A single ingested item from any source, before AI filtering.

    Dedup is enforced by the unique (source, external_id) pair — re-ingesting the same
    item is a no-op.
    """

    __table_args__ = (UniqueConstraint("source", "external_id", name="uq_source_external"),)

    id: int | None = Field(default=None, primary_key=True)
    source: str = Field(index=True)          # github | reddit | rss | forum | mcp | twitter | bluesky | numerai | stocktwits | careers
    source_key: str = Field(default="", index=True)  # stable per-resource provenance, e.g. github:owner/repo
    external_id: str
    url: str
    title: str
    body: str = ""
    author: str | None = None
    created_at: datetime | None = None       # timestamp from the source, when available
    fetched_at: datetime = Field(default_factory=_utcnow)
    content_hash: str = ""
    raw_json: str | None = None
    processed: bool = Field(default=False, index=True)


class SourceRegistry(SQLModel, table=True):
    """A discovered resource and its measured editorial quality."""

    __table_args__ = (UniqueConstraint("source_key", name="uq_source_registry_key"),)

    id: int | None = Field(default=None, primary_key=True)
    source_key: str = Field(index=True)
    adapter: str = Field(index=True)
    name: str
    url: str = ""
    target: str | None = None
    status: str = Field(default="active", index=True)  # candidate | active | suspended
    first_seen_at: datetime = Field(default_factory=_utcnow)
    last_seen_at: datetime = Field(default_factory=_utcnow, index=True)
    last_fetched_at: datetime | None = Field(default=None, index=True)
    failure_count: int = Field(default=0)


class Insight(SQLModel, table=True):
    """A synthesized, high-value insight distilled from a RawItem by the LLM."""

    id: int | None = Field(default=None, primary_key=True)
    raw_item_id: int = Field(foreign_key="rawitem.id", index=True)
    relevance_score: int = Field(index=True)
    category: str = Field(index=True)        # stores Category.value (trading style)
    approaches: str = "[]"                    # JSON array of Approach.value, e.g. ["Agentic AI"]
    technical_summary: str
    trader_impact: str
    model_used: str = ""
    created_at: datetime = Field(default_factory=_utcnow, index=True)


class DailyBrief(SQLModel, table=True):
    """The editorial layer for a given day's brief, stored as a JSON payload.

    Generated by the LLM at newsletter-write time and persisted so the live API can render
    the brief (which happens per request) without ever calling the LLM. One row per date.
    ``payload_json`` holds ``{theme, editor_note, picks: {insight_id: {summary}}}``.
    """

    id: int | None = Field(default=None, primary_key=True)
    brief_date: str = Field(index=True, unique=True)   # ISO date, e.g. "2026-07-17"
    payload_json: str
    model_used: str = ""
    generated_at: datetime = Field(default_factory=_utcnow)


class InsightExtraction(BaseModel):
    """Structured output contract every LLM provider must return for a raw item.

    Kept free of numeric/length JSON-schema constraints so it works with Claude's
    structured-output mode; the score range is validated in application code.
    """

    relevance_score: int = PydField(
        description="How useful this is to a self-directed retail/algo trader, 1 (noise) to 10 "
        "(genuinely actionable). Reward things a trader could actually try or use."
    )
    category: Category = PydField(
        description="The single trading style this best speaks to (Technical Analysis, Macro "
        "Analysis, Intraday Trading, Swing Trading, Fundamental Analysis, or Quant Firms)."
    )
    approaches: list[Approach] = PydField(
        default_factory=list,
        description="The 0-2 kinds of tech this item uses (Agentic AI, Machine Learning, "
        "Automation, Sentiment & News, Infrastructure & Data, Risk & Sizing). Empty if none fit.",
    )
    technical_summary: str = PydField(
        description="2-3 plain-English sentences a self-directed trader would understand: what it "
        "is and what it actually does. No academic jargon, no marketing fluff, no PhD math."
    )
    trader_impact: str = PydField(
        description="How a retail/independent trader could actually use this to trade better or "
        "make money — the concrete edge, tool, or workflow it unlocks."
    )
